### PR TITLE
Add CMake as optional buildsystem to Travis-CI

### PR DESCRIPTION
**Pull request by adrianbroher**
This PR should enable building both Autotools and CMake on Travis-CI. This should mostly address #9 and enable pulling CMake relevant PRs with more confidence.

This is the first time using the Travis-CI matrix feature so this PR may or may not work in the first attempt. Sorry for any future noise fixing this.

### CODE REVIEW

**Comment by adrianbroher** [comment]
Works as I would expect.

@rillian I assume your comment on #17 that the CMake build system test should be mandatory also applies to this PR, right?

**Comment by rillian** [comment]
> CMake build system test should be mandatory also applies to this PR, right?

I suppose so, yes.

**Comment by rillian** [comment]
The build breakage is not from your patch, afaict.

**Comment by adrianbroher** [comment]
> The build breakage is not from your patch, afaict.

Yes and this isn't the first time the autotools + gcc setup randomly combusts:

https://travis-ci.org/xiph/vorbis/jobs/165239981#L906
https://travis-ci.org/xiph/vorbis/jobs/120038320#L901

This version is most similar to the one reported:

https://travis-ci.org/xiph/vorbis/jobs/118982685#L1815

Maybe using the travis trusty image helps here:

https://docs.travis-ci.com/user/trusty-ci-environment/

**Comment by rillian** [comment]
I can reproduce this particular error locally. The issue seems to be that both the static html docs and the generated format specification declared a dependency on `fish_xiph_org.png`, so it ends up passed to doc_DATA twice. Automake doesn't appear to remove the duplicates and the install script complains about the overwrite. I've pushed a work-around.

It's interesting that the clang build doesn't seem to fail the same way. Different automake version, maybe?

**Comment by rillian** [comment]
Merged in 116f52575d136f002dd9db72b869c72c0cc6aa94. Thanks!

**Pull request closed without merging**
