### PR TITLE
Fix the compiling errors on msvc ARM64 configuration.

### PR DESCRIPTION
**Pull request by gongminmin**

### CODE REVIEW

**Comment by froydnj** [comment]
This apparently landed already, but it doesn't fix the compilation errors for me, because the x86-64 path here:

https://github.com/xiph/vorbis/blob/46e70fa6573e206c2555cd99a53204ffd6bf58fd/lib/os.h#L148-L150

needs an `_M_ARM64` guard as well, no?

**Comment by gongminmin** [comment]
Resubmit a fix for this.

**Comment by sezero** [comment]
This should be better fixed by https://github.com/xiph/vorbis/pull/47

**Comment by gongminmin** [comment]
Agree @sezero . #47 is cleaner and better. I'll withdraw this PR.

**Pull request closed without merging**
