### PR TITLE
fix typo introduced in commit 8d73daa

### PR DESCRIPTION
**Pull request by sezero**

### CODE REVIEW

**Comment by sezero** [comment]
PING?

**Comment by rillian** [comment]
Thanks for the fix! LGTM. The travis failure looks like we might have a race in the distcheck target, and shouldn't block the patch.

@tdaede, can you review too please? FWIW gcc 8.2.1 warns about this line.
```
lib/sharedbook.c:71:8: warning: statement with no effect [-Wunused-value]
     exp-63;
     ~~~^~~
```

**Comment by rillian** [comment]
r+

**Comment by sezero** [comment]
PING ?

**Comment by tdaede** [comment]
LGTM, merged, though there is actually a logic error further up that I'll also need to fix.

**Pull request closed without merging**
