### PR TITLE
[TravisCI]add build with clang

### PR DESCRIPTION
**Pull request by Chocobo1**

### CODE REVIEW

**Comment by rillian** [comment]
Thanks. Merged in 445e63f265d53a34ce3b41e5f247e49d8798e780.

Do you expect any variance between gcc and clang?

**Comment by Chocobo1** [comment]
>Do you expect any variance between gcc and clang?

AFAIK, not much for C code...

**Comment by rillian** [comment]
Yes, I wouldn't expect any difference for this library either. Why did you add it then?

**Comment by Chocobo1** [comment]
Just for the sake of actually test building with it. LOL.

**Comment by erikd** [comment]
For many of my projects, I build them with `-Wall -Werror` and then build them with Clang and GCC.

Clang and GCC do have different sets of warnings.

**Comment by rillian** [comment]
That's a good point. Looks like vorbis wants 'make debug' to build with -Wall. Should probably change that.

**Pull request merged**
